### PR TITLE
Fix some unit tests

### PR DESCRIPTION
**Pull request by martindiphoorn**

### CODE REVIEW

**Comment by benoitx** [comment]
Thanks for this Martin. It is greatly appreciated.

What do you think should happen to 'invalid' lines?
e.g. \"hello,world

At the moment it will parse as [hello,world], single column, no double quote...

and this one:
\"col1\",col2\",col3 returns col1 col2" col3

AAARRRRGGG

**Comment by benoitx** [comment]
My thinking is: leave the parsing of the line as is BUT have the DataSet parser detect if we have an ODD number of Qualifiers (e.g. " or | or whatever).  It is the number is odd -> Do not parse the line and raise an error, the line is malformed.  What do you think?

**Comment by martindiphoorn** [comment]
If i use a library like flatpack i would be happy that this decision is left to the user of the library. So I would make it a setting. Something like failOnError setting and skipLineOnErrror.

failOnError=true: Stop processing and raise an exception
failOnError=false: Check the skipLineOnError value
skipLineOnError=true: Skip the line if there is an error in it and continue
skipLineOnError=false: Do our best to get the right value

Just an idea, it gives the user some flexibility. And every use case is different.

Some examples:
```
col1,"col2",col3      // good
col1, "co""l2", col3  // good
"col1,col2,col3"       // valid, its just one column
"col1"",""col2,col3"  // valid, its just one column
"col1,coll2,col3        // invalid, when starting with qualifier it should end also  with it
col1",col2,col3         // invalid, end but no starting
co""l1,col2,col3        // invalid, if qualifiers are escaped the field should be wrapped with it
```
The big question is, what should be the best effort result?

**Comment by martindiphoorn** [comment]
Just thinking, should we create an seperate unit test for checking RFC compatibility?

https://www.ietf.org/rfc/rfc4180.txt

**Comment by benoitx** [comment]
Done: issue #36
https://github.com/Appendium/flatpack/issues/36

**Comment by benoitx** [comment]
Hi Martin
Thinking of doing a release but do you know how to build the Maven site with TRAVIS CI?  Getting stuck on this... Thanks
Benoit

**Comment by martindiphoorn** [comment]
Hi Benout,

i never used TRAVIS CI. I have experience with Gitlab CI.
If you can give me some pointers. I can look in to it.

Maritn

**Pull request merged**
